// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  default: {
    accordion: {
      name: "accordion",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/accordion.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/accordion.tsx"),
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
  },
};
